development: &default
  adapter: postgresql
  database: url_checker_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  host: localhost
  username: ildarsafin

test:
  <<: *default
  database: url_checker_test
  # need to mention the port so codeship can replace it
  port: 5432
